[toolchain]
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_distributor = "2KP1tES7htR1KGUuCQJPUbBhWrPAQtgyYAWrVenfYmN2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "deploy-wallet.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
